### ISSUE TITLE
keep database specific fields

### ISSUE THREAD

**Issue by maxswjeon** [zzau13/prisma-schema-transformer#179]
Currently, the database specific fields (such as `@db.Timestamp(6)` or `@db.Uuid()`) is removed after transform. Is there any way to keep them?

**Comment by aniravi24** [comment]
I was looking around to see if they provide that information in their API, but it looks like Prisma doesn't return this information in their API yet.

This package is built on the DMMF API from Prisma but the DMMF doesn't contain the native type attribute info.
 
https://github.com/prisma/prisma/issues/10252

**Comment by zzau13** [comment]
Can use https://github.com/prisma/prisma/issues/10252#issuecomment-1962758703 for parse `@db` and add it to the result. I've been very busy and the repository has been a bit forgotten. I will try to make time and implement this solution as soon as possible.
